<?php 
/**
 * CoolMS2 File module (http://www.coolms.com/)
 * 
 * @link      http://github.com/coolms/CmsFile for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsFile;

$this->fieldset = $this->form->get('user')->get('files');

?>
<?= $this->render('cms-file/file/form');
